// constants/strings.js
// Centralized string constants for i18n preparation

export const AUTH_STRINGS = {
  WELCOME_BACK: 'Welcome Back',
  SIGN_IN_TO_ACCOUNT: 'Sign in to your M1A account',
  CREATE_ACCOUNT: 'Create Account',
  SIGN_UP_TO_START: 'Sign up to get started with M1A',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ENTER_EMAIL: 'Enter your email',
  ENTER_PASSWORD: 'Enter your password',
  CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm your password',
  PASSWORD_REQUIREMENTS: 'Must be at least 8 characters with uppercase, lowercase, number, and special character',
  ACCOUNT_CREATED: 'Account Created!',
  ACCOUNT_CREATED_MESSAGE: 'Your account has been created successfully. Please check your email to verify your account.',
  PASSWORD_RESET_SENT: 'Password Reset Email Sent',
  PASSWORD_RESET_MESSAGE: 'Please check your email for instructions to reset your password.',
};

export const PROFILE_STRINGS = {
  PROFILE: 'Profile',
  EDIT_PROFILE: 'Edit Profile',
  DISPLAY_NAME: 'Display Name',
  USERNAME: 'Username',
  BIO: 'Bio',
  LOCATION: 'Location',
  WEBSITE: 'Website',
  CHANGE_PROFILE_PHOTO: 'Change Profile Photo',
  ADD_COVER_PHOTO: 'Add Cover Photo',
  CHANGE_COVER: 'Change Cover',
  BASIC_INFORMATION: 'Basic Information',
  SOCIAL_LINKS: 'Social Links',
  PRIVACY_SECURITY: 'Privacy & Security',
  CONNECT_SOCIAL: 'Connect your social media accounts',
  PRIVATE_PROFILE: 'Private Profile',
  PRIVATE_PROFILE_DESC: 'Only approved followers can see your posts',
  SHOW_ONLINE_STATUS: 'Show Online Status',
  SHOW_ONLINE_STATUS_DESC: "Let others see when you're online",
  ALLOW_MESSAGES: 'Allow Messages',
  ALLOW_MESSAGES_DESC: 'Let others send you direct messages',
  DARK_THEME: 'Dark Theme',
  DARK_THEME_DESC: 'Switch between light and dark mode',
  SAVE: 'Save',
  SAVING: 'Saving...',
  POSTS: 'Posts',
  MEDIA: 'Media',
  LIKES: 'Likes',
  FOLLOWERS: 'Followers',
  FOLLOWING: 'Following',
  NO_POSTS: 'No posts yet',
  NO_MEDIA: 'No media yet',
  NO_LIKED_POSTS: 'No liked posts yet',
  LOADING_POSTS: 'Loading posts...',
  CREATE_YOUR_PROFILE: 'Create your profile',
  PROFILE_SETUP_MESSAGE: "Let's set up your profile to get started.",
  GET_STARTED: 'Get started',
  UPLOADING: 'Uploading…',
  USERNAME_HELPER: '3-30 characters, letters, numbers, underscores, and hyphens only',
};

export const VALIDATION_STRINGS = {
  REQUIRED: 'Required',
  INVALID_FORMAT: 'Invalid format',
  TOO_SHORT: 'Too short',
  TOO_LONG: 'Too long',
  CHARACTERS_REMAINING: 'characters remaining',
};

export const GENERAL_STRINGS = {
  OK: 'OK',
  CANCEL: 'Cancel',
  CONTINUE: 'Continue',
  BACK: 'Back',
  NEXT: 'Next',
  DONE: 'Done',
  LOADING: 'Loading...',
  ERROR: 'Error',
  SUCCESS: 'Success',
  WARNING: 'Warning',
  INFO: 'Info',
};

